###############################################
#
#  Credit Card Transaction Generator Configs
#
###############################################

#target:
#  type: "kafka"
#  kafka: "localhost:9092"
#  topic: "test-topic2"

target:
  type: "json"
  transactionPerFile: 100000

configs:
  # accounts.json
  createAccountsJson: True
  # locations.json
  createLocationsJson: True

data:
  # Requires columns:
  #   Name|trxn_mean|trx_std
  retailers: "data/us_retailers.csv"
  # Requires columns:
  #   City|State short|City alias|Latitude|Longitude
  locations: "data/us_cities_states_counties_longlats_ga.csv"

generator:
  # accounts.json
  accountsNumber: 10000
  minTransactionAmountTarget: 10
  maxTransactionAmountTarget: 2000
  minTransactionRadiusTarget: 1
  maxTransactionRadiusTarget: 40

  # locations.json
  merchantsNumber: 5000

  # transactions
  transactionNumber: 2000000
  transationPercFraud: 0.01
  storeFraudFlag: False
  sleepBetweenIterations: 0.001

constraints:
  states: ["GA"]
