###############################################
#
#  Credit Card Transaction Generator Configs
#
###############################################

#target:
#  type: "kafka"
#  kafka: "localhost:9092"
#  topic: "test-topic2"

target:
  type: "json"
  transactionPerFile: 10000
  # Location to create
  transactionsFileLoctation: "data/"

configs:
  # accounts.json
  createAccountsJson: True
  # locations.json
  createLocationsJson: True

data:
  # Requires columns:
  #   Name|trxn_mean|trx_std
  retailers: "data/us_retailers.csv"
  # Requires columns:
  #   City|State short|City alias|Latitude|Longitude
  locations: "data/ga_locations.csv"


generator:
  # accounts.json
  accountsNumber: 2000
  minTransactionAmountTarget: 10
  maxTransactionAmountTarget: 1000
  minTransactionRadiusTarget: 1
  maxTransactionRadiusTarget: 40

  # locations.json
  merchantsNumber: 1000

  # transactions
  transactionNumber: 100000
  FraudEveryNTransactions: 100
  storeFraudFlag: True
  sleepBetweenIterations: 0

constraints:
  states: ["GA"]
